"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  Network,
  Lock,
  RefreshCcw,
  Settings,
  ThumbsUp,
  Link2,
  CheckCircle,
  Wallet,
  Shield,
} from "lucide-react";

import image1 from "../../public/01.png";
import image2 from "../../public/02.png";
import image3 from "../../public/03.png";
import image4 from "../../public/04.png";
import image5 from "../../public/05.png";

import { Smartphone, ShieldCheck } from "lucide-react";

import { KeyRound, BellRing, Fingerprint } from "lucide-react";
import {
  BadgePercent,
  Gift,
  Timer,
  HeartHandshake,
  FileCheck2,
  Banknote,
  ListChecks,
  Users,
  Receipt,
  Settings2,
  MessageSquareCode,
  Building2,
  MonitorSmartphone,
  Globe,
} from "lucide-react";

const gamingFintechs = [
  {
    title: "Ensuring Compliance with GST Laws",
    icon: FileCheck2,
    process:
      "GST verification is essential to confirm that the taxpayer or business is properly registered under the Goods and Services Tax Act and is compliant with the tax regulations. Businesses must be registered to collect GST on behalf of the government and claim tax credits.",
    example:
      "A manufacturer can only claim input tax credit on raw material purchases if they are registered under GST. Verification ensures that the manufacturer’s registration status is legitimate.",
  },
  {
    title: "Preventing GST Fraud",
    icon: ShieldCheck,
    process:
      "The Indian GST system is vulnerable to tax fraud where businesses may claim fraudulent tax credits or evade taxes. GST verification helps ensure that businesses are not using fake or non-existent GST numbers for fraudulent claims.",
    example:
      "Fake GST invoices might be generated by fraudulent suppliers to evade tax. By verifying the GST number, buyers can ensure that they are dealing with legitimate suppliers, reducing the risk of fraudulent transactions.",
  },
  {
    title: "Vendor and Supplier Authentication",
    icon: Users,
    process:
      "When engaging in business transactions, it is crucial to verify the GST registration of suppliers and vendors. This ensures that the business can properly claim input tax credit (ITC) for the goods and services purchased.",
    example:
      "A retailer purchasing goods from a supplier needs to verify the supplier's GST registration. Without verification, the retailer risks purchasing from an unregistered supplier, and in turn, may not be able to claim the input tax credit on the goods purchased.",
  },
  {
    title: "Avoiding Legal and Financial Penalties",
    icon: BadgePercent,
    process:
      "If businesses or individuals transact with non-compliant or unregistered entities, they could be subject to penalties or legal issues. GST authorities enforce strict penalties for conducting business with unregistered entities. Proper GST verification ensures that businesses avoid such risks.",
    example:
      "A contractor engaging an unregistered vendor may be liable to pay penalties and taxes if the vendor’s GST registration is found to be invalid. Verifying the GST number beforehand reduces the chances of such penalties.",
  },
  {
    title: "Streamlining the GST Filing Process",
    icon: Timer,
    process:
      "Accurate GST verification helps streamline the process of GST returns filing and tax reconciliation. Valid GST numbers and correct vendor information ensure that businesses file taxes correctly and avoid mismatches in their records.",
    example:
      "When filing the GST returns for a quarter, the business verifies the GST details of all suppliers. This ensures that all input tax credits (ITC) are properly accounted for, preventing discrepancies between the records and returns filed.",
  },
  {
    title: "Promoting Trust in Business Transactions",
    icon: HeartHandshake,
    process:
      "GST verification builds trust between businesses and their customers. By ensuring that suppliers and vendors are properly registered, businesses demonstrate their commitment to lawful operations, creating a reputation of trustworthiness in the market.",
    example:
      "A wholesaler who verifies the GST credentials of their suppliers assures their customers that they are working with compliant partners, fostering confidence and long-term business relationships.",
  },
  {
    title: "Enabling Smooth Business Operations",
    icon: MonitorSmartphone,
    process:
      "GST verification allows businesses to operate smoothly in the market by ensuring their dealings are legitimate and compliant. This helps prevent any future challenges with tax authorities, such as audits or investigations.",
    example:
      "An e-commerce platform that verifies the GST registration of its sellers ensures smooth business operations, avoiding conflicts with tax authorities and improving the overall customer experience.",
  },
  {
    title: "Facilitating Government Tax Collection and Transparency",
    icon: Globe,
    process:
      "Verifying GST details ensures that businesses contribute their fair share to the country's tax system, facilitating proper tax collection for government services and infrastructure development. It ensures that only registered and compliant businesses are part of the formal economy.",
    example:
      "When businesses import goods or services, GST verification helps confirm that the sellers are registered, ensuring that taxes are properly paid on imported goods.",
  },
  {
    title: "Access to Government Schemes and Benefits",
    icon: Gift,
    process:
      "Businesses that are registered under GST are eligible for certain government schemes, such as subsidies, tax breaks, or access to tender opportunities. GST verification confirms whether businesses are eligible for such benefits.",
    example:
      "A small business may be eligible for the GST Composition Scheme if it meets the criteria. By verifying the GST number, the business can access this scheme and benefit from a lower tax rate.",
  },
  {
    title: "Cross-Border Transactions and International Trade",
    icon: Banknote,
    process:
      "Businesses involved in cross-border trade or international supply chains need to verify GST details to ensure compliance with international tax standards. Verification allows seamless documentation and compliance for both domestic and foreign transactions.",
    example:
      "An exporter can verify the GST status of foreign suppliers or buyers to ensure that all goods traded are compliant with GST regulations and to avoid complications during customs clearance.",
  },
];

const Services = [
  {
    title: "Taxpayer Identification and Compliance",
    description:
      "PAN verification is crucial for identifying individuals and businesses who are required to pay taxes in India. Ensuring the validity of PAN helps in maintaining compliance with tax laws and preventing tax evasion.",
  },
  {
    title: "Preventing Fraud and Identity Theft",
    description:
      "PAN verification ensures that the person or entity using the PAN number is the legitimate owner. This prevents fraudulent activities such as the use of fake or stolen PAN numbers for financial transactions or tax evasion.",
  },
  {
    title: "Ensuring Financial Transparency",
    description:
      "PAN verification ensures that individuals or entities engaging in significant financial transactions are genuine and compliant with tax regulations, helping maintain financial transparency.",
  },
  {
    title: "KYC Compliance (Know Your Customer)",
    description:
      "Financial institutions and service providers require PAN verification during onboarding to meet KYC norms. It helps prevent fraud and confirms the customer's identity.",
  },
  {
    title: "Regulatory Compliance in Business Transactions",
    description:
      "PAN verification supports AML and CFT regulations in sectors like banking and real estate, ensuring that high-value transactions are conducted by legitimate entities.",
  },
  {
    title: "Avoiding Tax Evasion",
    description:
      "Linking income and financial transactions to a verified PAN reduces the risk of tax evasion by preventing the concealment of income or misreporting of financial data.",
  },
];

const features = [
  {
    title: "Online GST Verification Tools",
    icon: CheckCircle,
    process:
      "The GST portal offers direct and reliable GSTIN verification services to check the business name, address, and active/inactive status.",
    example:
      "Businesses use the GSTIN search tool on the official portal to verify vendor details before engaging in transactions.",
  },
  {
    title: "Third-Party Verification Platforms",
    icon: ListChecks,
    process:
      "Bulk verification platforms enable companies to validate multiple GSTINs simultaneously, increasing speed and operational efficiency.",
    example:
      "A corporate procurement team verifies the GST status of many vendors at once using a third-party bulk verification tool.",
  },
  {
    title: "Automated ERP Integration",
    icon: Settings2,
    process:
      "ERP systems can integrate GST APIs to verify GSTINs during vendor onboarding, reducing manual errors and ensuring real-time compliance.",
    example:
      "A manufacturer integrates GST validation into its ERP to auto-check suppliers' GST numbers during purchase order creation.",
  },
  {
    title: "Real-Time GST Validation at POS",
    icon: Receipt,
    process:
      "Retail POS systems can validate GSTINs in real time during billing or invoicing, ensuring proper tax compliance and documentation.",
    example:
      "A supermarket validates a vendor’s GSTIN at checkout to apply the correct tax and ensure vendor legitimacy.",
  },
  {
    title: "Bulk GST Verification for Financial Institutions",
    icon: Building2,
    process:
      "Banks and financial institutions verify GSTINs of businesses for KYC and regulatory compliance, especially before loan approvals or partnerships.",
    example:
      "A bank validates a business applicant’s GSTIN to ensure legitimacy before sanctioning a business loan.",
  },
  {
    title: "SMS and Email OTP Verification",
    icon: MessageSquareCode,
    process:
      "Some verification processes include sending OTPs via SMS/email to authenticate GSTIN registration, adding an extra security layer.",
    example:
      "A tax consultant sends an OTP to a client's registered number to validate the GSTIN during compliance checks.",
  },
];

const blockchains = [
  {
    icon: Network,
    title: "Decentralization",
    description:
      "Blockchain operates on a decentralized network of computers (nodes), where no single entity has control over the entire system. This ensures trust, transparency, and accountability by distributing control and verification across multiple participants.",
  },
  {
    icon: RefreshCcw,
    title: "Distributed Ledger",
    description:
      "The blockchain is essentially a distributed ledger where records, known as blocks, are linked together in a chain. Each block contains data about transactions or other types of information, and the blocks are cryptographically secured, making the ledger immutable.",
  },
  {
    icon: Lock,
    title: "Cryptography",
    description:
      "Cryptography plays a crucial role in blockchain development, ensuring that data stored in the blockchain is secure, encrypted, and only accessible by authorized parties. Each block is encrypted with a cryptographic hash, and users' transactions are protected by digital signatures.",
  },
  {
    icon: Settings,
    title: "Smart Contracts",
    description:
      "Blockchain development also includes the creation of smart contracts, which are self-executing contracts with predefined rules encoded directly onto the blockchain. Smart contracts automatically enforce agreements when certain conditions are met, eliminating the need for intermediaries and reducing the risk of human error or fraud.",
  },
  {
    icon: ThumbsUp,
    title: "Consensus Algorithms",
    description:
      "Consensus mechanisms ensure that all the nodes on the blockchain network agree on the validity of transactions. Popular consensus algorithms include Proof of Work (PoW), Proof of Stake (PoS), and Delegated Proof of Stake (DPoS), each offering different methods to validate and add transactions to the blockchain.",
  },
  {
    icon: Wallet,
    title: "Tokenization",
    description:
      "Blockchain development can include the creation of digital assets or tokens, which can represent ownership or access to services. Tokens can be used for various purposes, including cryptocurrencies (like Bitcoin or Ethereum), security tokens, or utility tokens within decentralized applications (dApps).",
  },
  {
    icon: Link2,
    title: "Interoperability",
    description:
      "Blockchain development often involves ensuring that different blockchain systems can communicate with each other, enabling interoperability between separate blockchains. This is especially important in multi-chain ecosystems where assets and data need to flow seamlessly between platforms.",
  },
];

const landingwebsites = [
  {
    image: image1,
    title: "Telecommunications",
    description:
      "Mobile phone providers or broadband companies can offer an easy way for customers to recharge their prepaid accounts or add additional services (data, voice plans, etc.).",
  },
  {
    image: image2,
    title: "Utility Companies",
    description:
      "Providers of electricity, water, gas, or other utilities can use the portal to allow customers to pay bills or recharge prepaid meters, providing a seamless payment experience.",
  },
  {
    image: image3,
    title: "Entertainment & Streaming Services",
    description:
      "Subscription-based platforms (such as music, video, or gaming services) can enable users to quickly top-up their accounts or manage subscription renewals through the portal.",
  },
  {
    image: image4,
    title: "Gift Cards and Vouchers",
    description:
      "Businesses offering digital gift cards or promotional vouchers can implement the portal to allow customers to recharge their prepaid balances.    ",
  },
  {
    image: image5,
    title: "E-Commerce and Retail",
    description:
      "Online retailers and e-commerce platforms can integrate a recharge portal to allow users to top-up their accounts for purchases or to add balance to wallets.",
  },
];
const Stages = [
  {
    id: 1,
    title: "Errors in PAN Database",
    objectives: [
      "Inaccuracies in the PAN database, such as incorrect names, addresses, or mismatched details, can result in failed verification attempts. This can cause delays in processes like loan approvals or tax filings.",
    ],
  },
  {
    id: 2,
    title: "Privacy Concerns",
    objectives: [
      "PAN verification involves sensitive personal and financial information. There is a risk of unauthorized access to PAN data, leading to privacy violations or misuse of information.",
    ],
  },
  {
    id: 3,
    title: "Technical Issues",
    objectives: [
      "PAN verification may fail if there is a mismatch between the details provided and the records in the government database or if the verification system is not working properly.",
    ],
  },
];

const methods = [
  {
    icon: <Smartphone className="text-primary w-6 h-6" />,
    title: "SMS-Based Authentication",
    description:
      "OTP sent via SMS to your registered number. Convenient but vulnerable to SIM swapping.",
  },
  {
    icon: <KeyRound className="text-primary w-6 h-6" />,
    title: "Authenticator App",
    description:
      "Use apps like Google Authenticator for time-based OTPs that refresh every 30 seconds.",
  },
  {
    icon: <BellRing className="text-primary w-6 h-6" />,
    title: "Push Notification",
    description:
      "Get a push notification on your phone and approve login requests instantly.",
  },
  {
    icon: <ShieldCheck className="text-primary w-6 h-6" />,
    title: "Hardware Tokens",
    description:
      "Insert a USB security key like YubiKey to complete authentication securely.",
  },
  {
    icon: <Fingerprint className="text-primary w-6 h-6" />,
    title: "Biometric Authentication",
    description:
      "Authenticate using fingerprint, facial recognition, or retina scan.",
  },
];

export default function GstVerirfication() {
  const itemVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
  };
  return (
    <div className="pt-16">
      {/* Hero Section */}
      <section className="py-24 relative hero-pattern">
        <div className="absolute inset-0 bg-gradient-to-b from-background via-background/95 to-background"></div>
        <div className="container relative z-10">
          <div className="max-w-4xl mx-auto text-center">
            <motion.span
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6"
            >
              GST Verification Services
            </motion.span>
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="text-4xl md:text-6xl font-bold mb-6 "
            >
              GST Verification
            </motion.h1>
          </div>
        </div>
      </section>
      <section className="relative py-24 px-6 md:px-12   overflow-hidden">
        <div className="bg-background/100 mb-16 p-8 rounded-xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            viewport={{ once: true }}
            className="text-3xl md:text-3xl font-bold mb-6 bg-clip-text"
          >
            PAN Verification: Need and Benefits
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2, ease: "easeOut" }}
            viewport={{ once: true }}
            className="text-muted-foreground   text-lg md:text-xl leading-relaxed"
          >
            GST (Goods and Services Tax) is a single, unified indirect tax
            system implemented in India to streamline the taxation structure and
            replace multiple taxes levied by central and state governments.
            Businesses and individuals engaged in the sale, supply, or purchase
            of goods and services are required to obtain GST registration and
            comply with tax obligations. GST verification refers to the process
            of confirming the legitimacy and accuracy of the GST registration
            details provided by businesses, taxpayers, or vendors. This
            verification process is crucial for ensuring tax compliance,
            preventing fraud, and improving the integrity of the GST system..
          </motion.p>
        </div>
      </section>
      <section className="relative py-24 px-6 md:px-12 bg-gradient-to-b to-background/80 overflow-hidden">
        {/* Subtle background pattern */}
        <div className="absolute inset-0 bg-grid-pattern opacity-5 pointer-events-none" />

        <div className="container mx-auto relative z-10">
          <div className="text-center mb-16">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              viewport={{ once: true }}
              className="text-4xl md:text-5xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60"
            >
              Need for GST Verification
            </motion.h2>
          </div>

          {/* Cards Grid */}
          <motion.div
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            {gamingFintechs.map((item, index) => {
              const IconComponent = item.icon;
              return (
                <motion.div
                  key={item.title}
                  variants={itemVariants}
                  className="group"
                >
                  <Card className="relative bg-secondary/30 border-border/30 h-full transition-all duration-500 group-hover:shadow-xl group-hover:border-primary/50 group-hover:bg-secondary/50 overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-t from-primary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

                    <CardContent className="p-8 relative z-10">
                      <div className="rounded-full bg-primary/10 p-4 w-16 h-16 mx-auto mb-6 flex items-center justify-center transform group-hover:scale-110 transition-transform duration-300">
                        <IconComponent className="h-8 w-8 text-primary group-hover:text-primary-foreground transition-colors duration-300" />
                      </div>

                      <h3 className="text-xl md:text-2xl text-center font-semibold mb-3 text-foreground group-hover:text-primary transition-colors duration-300">
                        {item.title}
                      </h3>

                      {/* Dynamic Fields Rendering */}
                      <p className="text-muted-foreground text-base leading-relaxed mb-2">
                        {item.process}
                      </p>

                      <p className="text-muted-foreground text-base leading-relaxed">
                        <span className="text-white font-semibold">
                          Example:
                        </span>{" "}
                        {item.example}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </motion.div>
        </div>
      </section>
     

      {/* Features Section */}
      <section className="relative py-24 px-6 md:px-12 bg-gradient-to-b from-background to-background/80 overflow-hidden">
        {/* Subtle background pattern */}
        <div className="absolute inset-0 bg-grid-pattern opacity-5 pointer-events-none" />

        <div className="container mx-auto relative z-10">
          {/* Header Section */}
          <div className="text-center mb-16">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              viewport={{ once: true }}
              className="text-4xl md:text-5xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60"
            >
              Solutions for Efficient GST Verification
            </motion.h2>
          </div>

          {/* Features Grid */}
          <motion.div
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            {features.map((item, index) => {
              const IconComponent = item.icon;
              return (
                <motion.div
                  key={item.title}
                  variants={itemVariants}
                  className="group"
                >
                  <Card className="relative bg-secondary/30 border-border/30 h-full transition-all duration-500 group-hover:shadow-xl group-hover:border-primary/50 group-hover:bg-secondary/50 overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-t from-primary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

                    <CardContent className="p-8 relative z-10">
                      <div className="rounded-full bg-primary/10 p-4 w-16 h-16 mx-auto mb-6 flex items-center justify-center transform group-hover:scale-110 transition-transform duration-300">
                        <IconComponent className="h-8 w-8 text-primary group-hover:text-primary-foreground transition-colors duration-300" />
                      </div>

                      <h3 className="text-xl md:text-2xl text-center font-semibold mb-3 text-foreground group-hover:text-primary transition-colors duration-300">
                        {item.title}
                      </h3>

                      {/* Dynamic Fields Rendering */}
                      <p className="text-muted-foreground text-base leading-relaxed mb-2">
                        {item.process}
                      </p>

                      <p className="text-muted-foreground text-base leading-relaxed">
                        <span className="text-white font-semibold">
                          Example:
                        </span>{" "}
                        {item.example}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </motion.div>
        </div>
      </section>

      {/* Services Section */}
      <section className="relative py-24 px-6 md:px-12   overflow-hidden">
        <div className="bg-background/100 mb-16 p-8 rounded-xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            viewport={{ once: true }}
            className="text-3xl md:text-3xl font-bold mb-6 bg-clip-text text-primary text-center"
          >
            Conclusion
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2, ease: "easeOut" }}
            viewport={{ once: true }}
            className="text-muted-foreground   text-lg md:text-xl leading-relaxed"
          >
            GST verification is essential for maintaining transparency,
            preventing fraud, ensuring compliance, and promoting trust in the
            business ecosystem. It is necessary for businesses to verify GSTINs
            regularly to ensure that their transactions, vendors, and suppliers
            are legitimate and compliant with tax laws. Leveraging online
            verification tools, automated systems, and integrating GST
            verification into business processes enhances efficiency, reduces
            errors, and promotes smooth, legally-compliant operations. As GST
            continues to be a cornerstone of India's tax system, ensuring
            accurate GST verification will remain crucial for businesses to
            avoid penalties and streamline their operations.
          </motion.p>
        </div>
      </section>
    </div>
  );
}
